# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
      - development
  paths:
    include:
      - "website/*"

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
 
- task: Npm@1  
  displayName: 'Angular CLI 17.3.2' 
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install -g @angular/cli@17.3.2'

- task: Npm@1  
  displayName: ' @angular-devkit/build-angular' 
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install --save-dev @angular-devkit/build-angular'

- task: Npm@1
  displayName: Build
  inputs:
    command: custom
    verbose: false
    customCommand: 'ng build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "dist"
    ArtifactName: "wireservers-web-artifacts"
