# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
 
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
 
- task: Npm@1  
  displayName: 'Angular CLI 15.0.3'  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install -g @angular/cli@15.0.3'

- task: Npm@1  
  displayName: ' @angular-devkit/build-angular'  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install --save-dev @angular-devkit/build-angular --legacy-peer-deps'

- task: Npm@1
  displayName: Build
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: CopyPublishBuildArtifacts@1
  displayName: 'Copy Publish Artifact: angular-web-app'
  inputs:
        CopyRoot: /dist
        Contents: '**'
        ArtifactName: wireservers-web-app 
        ArtifactType: Container