# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - "development"
  paths:
    include:
      - wireservers.com/website

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - task: Npm@1
    displayName: "Running npm install for packages"
    inputs:
      command: "install"รฅรง
      workingDir: "website"
      verbose: true

  - task: CmdLine@2
    inputs:
      script: "node ./node_modules/.bin/ng build"
      workingDirectory: "website"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "website/dist"
      ArtifactName: "wireservers-website-artifacts"
